

all: esrin

esrin:   ast.cpp esrin.cpp generate.cpp list.cpp parse.cpp sehvler.cpp stek.cpp symtab.cpp token.cpp defs.h esrin.h rules_data_base.h sehvler.h states.h
	g++ ast.cpp esrin.cpp generate.cpp list.cpp parse.cpp sehvler.cpp stek.cpp symtab.cpp token.cpp -o cmpl

